pipeline:
  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      branch: rollback/v1
      event: push
   image_to_quay:
    image: docker:17.09.1
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag app-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/end-tenancy:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/end-tenancy:$${DRONE_COMMIT_SHA}
    when:
      branch: rollback/v1
      event: push
