pipeline:

  build_6:
    image: node:6
    commands:
      - npm --loglevel warn install
      - npm test

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app .
    when:
      event: pull_request

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app .
    when:
      branch: master

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance .
    when:
      event: pull_request

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance .
    when:
      branch: master

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -d --net host --userns host app
      - docker run --rm --net host --userns host acceptance
    when:
      event: pull_request

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -e NODE_ENV=ci -e DISABLE_CSP=true -d --net host --userns host app
      - docker run --rm --net host --userns host acceptance
    when:
      branch: master

  image_to_quay:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag app quay.io/ukhomeofficedigital/end-tenancy:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/end-tenancy:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_end-tenancy_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-end-tenancy
    branch: master
    deploy_to: dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=end-tenancy-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_end-tenancy_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-end-tenancy
    branch: master
    deploy_to: preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=end-tenancy-preprod
    when:
      event: deployment
      environment: preprod

  trigger_deploy_to_end-tenancy_prod:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-end-tenancy
    branch: master
    deploy_to: prod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=end-tenancy-prod
    when:
      event: deployment
      environment: prod

services:
  redis:
    image: redis
