language: node_js
node_js:
  - "6"

services:
  - docker
  - redis

before_install:
  - npm cache clean
  - docker build --tag travis .
  - docker run -d --net=host -e NODE_ENV=ci -e DISABLE_CSP=true travis

script:
  - npm test && npm run test:acceptance

notifications:
  email: false
