FROM node:24.16.0-alpine3.23@sha256:9a2c6269f83d74af45665c0b738b78c7b5f07bf2374c72a4c540065a975b9693

USER root

# Switch to UK Alpine mirrors, update package index and upgrade all installed packages
RUN echo "http://uk.alpinelinux.org/alpine/v3.23/main" > /etc/apk/repositories ; \
    echo "http://uk.alpinelinux.org/alpine/v3.23/community" >> /etc/apk/repositories ; \
    apk update && apk upgrade --no-cache
    
# Setup nodejs group & nodejs user
RUN addgroup --system nodejs --gid 998 && \
    adduser --system nodejs --uid 999 --home /test/ && \
    chown -R 999:998 /test/

USER 999

WORKDIR /test

COPY --chown=999:998 . /test

RUN yarn install --frozen-lockfile && \
    yarn run postinstall

CMD npm run test:acceptance
