---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-internal-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-internal
  {{ end }}
{{ file .INGRESS_INTERNAL_ANNOTATIONS | indent 2 }}
spec:
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .DRONE_BUILD_NUMBER }}.internal.end-tenancy-branch.homeoffice.gov.uk
        - {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.internal.end-tenancy-branch.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
        - ending-a-tenancy.uat.internal.sas-notprod.homeoffice.gov.uk
      {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
        - stg.internal.ending-a-tenancy.sas.homeoffice.gov.uk
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: {{ .APP_NAME }}-internal-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      secretName: {{ .APP_NAME }}-internal
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.internal.end-tenancy-branch.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
    - host: ending-a-tenancy.uat.internal.sas-notprod.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
    - host: stg.internal.ending-a-tenancy.sas.homeoffice.gov.uk
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: {{ .APP_NAME }}
              {{ end }}
              servicePort: 10443
