// Generated from: e2e-tests\features\ukviet.feature
import { test } from "../../../e2e-tests/fixture/fixtures.ts";

test.describe('UKVIET - UkVI Ending of Tenancy', () => {

  test.beforeEach('Background', async ({ Given }, testInfo) => { if (testInfo.error) return;
    await Given('Test data has been created for "UKVIET" scenarios'); 
  });
  
  test.describe('UKVIET Ending of Tenancy 1 - E2E', () => {

    test('Example #1', { tag: ['@UkvietRegression', '@UkvietRegressionCI', '@ukviet-e2e', '@journey-request'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "1" - "Request a notice - Multiple tenants - Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Request a notice - Multiple tenants - Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #2', { tag: ['@UkvietRegression', '@UkvietRegressionCI', '@ukviet-e2e', '@journey-request'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "2" - "Request a notice - Single tenant - Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Request a notice - Single tenant - Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #3', { tag: ['@UkvietRegression', '@UkvietRegressionCI', '@ukviet-e2e', '@journey-request'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "3" - "Request a notice - Single tenant - Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Request a notice - Single tenant - Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #4', { tag: ['@UkvietRegression', '@UkvietRegressionCI', '@ukviet-e2e', '@journey-check'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "4" - "Disqualified person left property - Multiple tenants - Checking Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Disqualified person left property - Multiple tenants - Checking Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #5', { tag: ['@UkvietRegression', '@UkvietRegressionCI', '@ukviet-e2e', '@journey-check'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "5" - "Report disqualified person left property  - Multiple tenants - Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Report disqualified person left property  - Multiple tenants - Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

  });

  test.describe('UKVIET Ending of Tenancy 2 - E2E', () => {

    test('Example #1', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-check'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "6" - "Request a notice - Multiple tenants - Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Request a notice - Multiple tenants - Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #2', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-check'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "7" - "Disqualified person left property - Multiple tenants - Checking Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Disqualified person left property - Multiple tenants - Checking Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #3', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-check'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "8" - "Disqualified person left property - Single tenant - Checking Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Disqualified person left property - Single tenant - Checking Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #4', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-report'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "9" - "Disqualified person left property - Single tenant - Checking Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Disqualified person left property - Single tenant - Checking Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #5', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-report'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "10" - "Report disqualified person left property - Single tenant - Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Report disqualified person left property - Single tenant - Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #6', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-report'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "11" - "Report disqualified person left property - Multiple tenants - Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Report disqualified person left property - Multiple tenants - Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

    test('Example #7', { tag: ['@UkvietRegression', '@ukviet-e2e', '@journey-report'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "12" - "Report disqualified person left property - Single tenant - Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Report disqualified person left property - Single tenant - Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
    });

  });

  test('UKVIET Ending of Tenancy - Change your answers in Check answers page', { tag: ['@UkvietRegression', '@journey-request', '@change-answer'] }, async ({ Given, When, Then, And, pages }) => { 
    await Given('I selected the data for scenario "1" - "Request a notice - Multiple tenants - Landlord"'); 
    await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
    await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
    await Then('I check my answers for Ukviet - "Request a notice - Multiple tenants - Landlord"', null, { pages }); 
    await When('I change the tenancy start date to "18/10/2022" and continue', null, { pages }); 
    await Then('I check the tenancy start date is updated to "18/10/2022" on the Check your answers page', null, { pages }); 
    await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
  });

  test.describe('UKVIET Navigate to home page <Description>', () => {

    test('UKVIET Navigate to home page Request a notice - Multiple tenants - Landlord', { tag: ['@UkvietRegression', '@navigate-home', '@journey-request'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "1" - "Request a notice - Multiple tenants - Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Request a notice - Multiple tenants - Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
      await And('I am able to navigate back to home page', null, { pages }); 
    });

    test('UKVIET Navigate to home page Disqualified person left property - Multiple tenants - Checking Landlord', { tag: ['@UkvietRegression', '@navigate-home', '@journey-check'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "5" - "Disqualified person left property - Multiple tenants - Checking Landlord"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Disqualified person left property - Multiple tenants - Checking Landlord"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
      await And('I am able to navigate back to home page', null, { pages }); 
    });

    test('UKVIET Navigate to home page Report disqualified person left property  - Multiple tenants - Agent', { tag: ['@UkvietRegression', '@navigate-home', '@journey-report'] }, async ({ Given, When, Then, And, pages }) => { 
      await Given('I selected the data for scenario "9" - "Report disqualified person left property  - Multiple tenants - Agent"'); 
      await When('I visit the Ukviet ending of tenancy page', null, { pages }); 
      await And('I fill out my answers for the Ukviet questionnaire', null, { pages }); 
      await Then('I check my answers for Ukviet - "Report disqualified person left property  - Multiple tenants - Agent"', null, { pages }); 
      await And('I am able to submit the Ukviet questionnaire', null, { pages }); 
      await And('I am able to navigate back to home page', null, { pages }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('e2e-tests\\features\\ukviet.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":17,"tags":["@UkvietRegression","@UkvietRegressionCI","@ukviet-e2e","@journey-request"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"1\" - \"Request a notice - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"1\"","children":[{"start":34,"value":"1","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Request a notice - Multiple tenants - Landlord\"","children":[{"start":40,"value":"Request a notice - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Request a notice - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Request a notice - Multiple tenants - Landlord\"","children":[{"start":33,"value":"Request a notice - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":20,"pickleLine":18,"tags":["@UkvietRegression","@UkvietRegressionCI","@ukviet-e2e","@journey-request"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"2\" - \"Request a notice - Single tenant - Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"2\"","children":[{"start":34,"value":"2","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Request a notice - Single tenant - Agent\"","children":[{"start":40,"value":"Request a notice - Single tenant - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Request a notice - Single tenant - Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Request a notice - Single tenant - Agent\"","children":[{"start":33,"value":"Request a notice - Single tenant - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":28,"pickleLine":19,"tags":["@UkvietRegression","@UkvietRegressionCI","@ukviet-e2e","@journey-request"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"3\" - \"Request a notice - Single tenant - Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"3\"","children":[{"start":34,"value":"3","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Request a notice - Single tenant - Landlord\"","children":[{"start":40,"value":"Request a notice - Single tenant - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Request a notice - Single tenant - Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Request a notice - Single tenant - Landlord\"","children":[{"start":33,"value":"Request a notice - Single tenant - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":24,"tags":["@UkvietRegression","@UkvietRegressionCI","@ukviet-e2e","@journey-check"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"4\" - \"Disqualified person left property - Multiple tenants - Checking Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"4\"","children":[{"start":34,"value":"4","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Disqualified person left property - Multiple tenants - Checking Agent\"","children":[{"start":40,"value":"Disqualified person left property - Multiple tenants - Checking Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":39,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Disqualified person left property - Multiple tenants - Checking Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Disqualified person left property - Multiple tenants - Checking Agent\"","children":[{"start":33,"value":"Disqualified person left property - Multiple tenants - Checking Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":44,"pickleLine":25,"tags":["@UkvietRegression","@UkvietRegressionCI","@ukviet-e2e","@journey-check"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"5\" - \"Report disqualified person left property  - Multiple tenants - Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"5\"","children":[{"start":34,"value":"5","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Report disqualified person left property  - Multiple tenants - Agent\"","children":[{"start":40,"value":"Report disqualified person left property  - Multiple tenants - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Report disqualified person left property  - Multiple tenants - Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Report disqualified person left property  - Multiple tenants - Agent\"","children":[{"start":33,"value":"Report disqualified person left property  - Multiple tenants - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":56,"pickleLine":37,"tags":["@UkvietRegression","@ukviet-e2e","@journey-check"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"6\" - \"Request a notice - Multiple tenants - Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"6\"","children":[{"start":34,"value":"6","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Request a notice - Multiple tenants - Agent\"","children":[{"start":40,"value":"Request a notice - Multiple tenants - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":58,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Request a notice - Multiple tenants - Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Request a notice - Multiple tenants - Agent\"","children":[{"start":33,"value":"Request a notice - Multiple tenants - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":64,"pickleLine":38,"tags":["@UkvietRegression","@ukviet-e2e","@journey-check"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"7\" - \"Disqualified person left property - Multiple tenants - Checking Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"7\"","children":[{"start":34,"value":"7","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Disqualified person left property - Multiple tenants - Checking Landlord\"","children":[{"start":40,"value":"Disqualified person left property - Multiple tenants - Checking Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Disqualified person left property - Multiple tenants - Checking Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Disqualified person left property - Multiple tenants - Checking Landlord\"","children":[{"start":33,"value":"Disqualified person left property - Multiple tenants - Checking Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":72,"pickleLine":39,"tags":["@UkvietRegression","@ukviet-e2e","@journey-check"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"8\" - \"Disqualified person left property - Single tenant - Checking Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"8\"","children":[{"start":34,"value":"8","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Disqualified person left property - Single tenant - Checking Agent\"","children":[{"start":40,"value":"Disqualified person left property - Single tenant - Checking Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":74,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Disqualified person left property - Single tenant - Checking Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Disqualified person left property - Single tenant - Checking Agent\"","children":[{"start":33,"value":"Disqualified person left property - Single tenant - Checking Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":80,"pickleLine":44,"tags":["@UkvietRegression","@ukviet-e2e","@journey-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"9\" - \"Disqualified person left property - Single tenant - Checking Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"9\"","children":[{"start":34,"value":"9","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Disqualified person left property - Single tenant - Checking Landlord\"","children":[{"start":40,"value":"Disqualified person left property - Single tenant - Checking Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Disqualified person left property - Single tenant - Checking Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Disqualified person left property - Single tenant - Checking Landlord\"","children":[{"start":33,"value":"Disqualified person left property - Single tenant - Checking Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":88,"pickleLine":45,"tags":["@UkvietRegression","@ukviet-e2e","@journey-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"10\" - \"Report disqualified person left property - Single tenant - Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"10\"","children":[{"start":34,"value":"10","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Report disqualified person left property - Single tenant - Landlord\"","children":[{"start":41,"value":"Report disqualified person left property - Single tenant - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":90,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":92,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Report disqualified person left property - Single tenant - Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Report disqualified person left property - Single tenant - Landlord\"","children":[{"start":33,"value":"Report disqualified person left property - Single tenant - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":96,"pickleLine":46,"tags":["@UkvietRegression","@ukviet-e2e","@journey-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"11\" - \"Report disqualified person left property - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"11\"","children":[{"start":34,"value":"11","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Report disqualified person left property - Multiple tenants - Landlord\"","children":[{"start":41,"value":"Report disqualified person left property - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":98,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":100,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Report disqualified person left property - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Report disqualified person left property - Multiple tenants - Landlord\"","children":[{"start":33,"value":"Report disqualified person left property - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":101,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":104,"pickleLine":47,"tags":["@UkvietRegression","@ukviet-e2e","@journey-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":105,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"12\" - \"Report disqualified person left property - Single tenant - Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"12\"","children":[{"start":34,"value":"12","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Report disqualified person left property - Single tenant - Agent\"","children":[{"start":41,"value":"Report disqualified person left property - Single tenant - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":108,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Report disqualified person left property - Single tenant - Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Report disqualified person left property - Single tenant - Agent\"","children":[{"start":33,"value":"Report disqualified person left property - Single tenant - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":114,"pickleLine":50,"tags":["@UkvietRegression","@journey-request","@change-answer"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":115,"gherkinStepLine":51,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"1\" - \"Request a notice - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"1\"","children":[{"start":34,"value":"1","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Request a notice - Multiple tenants - Landlord\"","children":[{"start":40,"value":"Request a notice - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":116,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":117,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":118,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Request a notice - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Request a notice - Multiple tenants - Landlord\"","children":[{"start":33,"value":"Request a notice - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":119,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When I change the tenancy start date to \"18/10/2022\" and continue","stepMatchArguments":[{"group":{"start":35,"value":"\"18/10/2022\"","children":[{"start":36,"value":"18/10/2022","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":120,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then I check the tenancy start date is updated to \"18/10/2022\" on the Check your answers page","stepMatchArguments":[{"group":{"start":45,"value":"\"18/10/2022\"","children":[{"start":46,"value":"18/10/2022","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":121,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]}]},
  {"pwTestLine":126,"pickleLine":70,"tags":["@UkvietRegression","@navigate-home","@journey-request"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":127,"gherkinStepLine":61,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"1\" - \"Request a notice - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"1\"","children":[{"start":34,"value":"1","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Request a notice - Multiple tenants - Landlord\"","children":[{"start":40,"value":"Request a notice - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":128,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":129,"gherkinStepLine":63,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Request a notice - Multiple tenants - Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Request a notice - Multiple tenants - Landlord\"","children":[{"start":33,"value":"Request a notice - Multiple tenants - Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":131,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"And I am able to navigate back to home page","stepMatchArguments":[]}]},
  {"pwTestLine":135,"pickleLine":75,"tags":["@UkvietRegression","@navigate-home","@journey-check"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":61,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"5\" - \"Disqualified person left property - Multiple tenants - Checking Landlord\"","stepMatchArguments":[{"group":{"start":33,"value":"\"5\"","children":[{"start":34,"value":"5","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Disqualified person left property - Multiple tenants - Checking Landlord\"","children":[{"start":40,"value":"Disqualified person left property - Multiple tenants - Checking Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":137,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":138,"gherkinStepLine":63,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":139,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Disqualified person left property - Multiple tenants - Checking Landlord\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Disqualified person left property - Multiple tenants - Checking Landlord\"","children":[{"start":33,"value":"Disqualified person left property - Multiple tenants - Checking Landlord","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":140,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":141,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"And I am able to navigate back to home page","stepMatchArguments":[]}]},
  {"pwTestLine":144,"pickleLine":80,"tags":["@UkvietRegression","@navigate-home","@journey-report"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Test data has been created for \"UKVIET\" scenarios","isBg":true,"stepMatchArguments":[{"group":{"start":31,"value":"\"UKVIET\"","children":[{"start":32,"value":"UKVIET","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":145,"gherkinStepLine":61,"keywordType":"Context","textWithKeyword":"Given I selected the data for scenario \"9\" - \"Report disqualified person left property  - Multiple tenants - Agent\"","stepMatchArguments":[{"group":{"start":33,"value":"\"9\"","children":[{"start":34,"value":"9","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Report disqualified person left property  - Multiple tenants - Agent\"","children":[{"start":40,"value":"Report disqualified person left property  - Multiple tenants - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":146,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When I visit the Ukviet ending of tenancy page","stepMatchArguments":[]},{"pwStepLine":147,"gherkinStepLine":63,"keywordType":"Action","textWithKeyword":"And I fill out my answers for the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":148,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"Then I check my answers for Ukviet - \"Report disqualified person left property  - Multiple tenants - Agent\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Report disqualified person left property  - Multiple tenants - Agent\"","children":[{"start":33,"value":"Report disqualified person left property  - Multiple tenants - Agent","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":149,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"And I am able to submit the Ukviet questionnaire","stepMatchArguments":[]},{"pwStepLine":150,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"And I am able to navigate back to home page","stepMatchArguments":[]}]},
]; // bdd-data-end