export const ConstantsLib = {
  FULL_NAME: 'HOF TEST',
  B_FULL_NAME: 'HOF Tenant1',
  C_FULL_NAME: 'HOF Tenant2',
  D_FULL_NAME: 'HOF Tenant Left',
  LAND_LORD_AGENT_NAME: 'HOF LandLord Agent',
  LANDLORD_NAME: 'HOF LandLord',
  COMPANY_NAME: 'Test UK Ltd',
  ADDRESS_LINE_1: '100',
  ADDRESS_LINE_2: 'Tenth St',
  TOWN_OR_CITY: 'HULL',
  POSTCODE: 'M11 1HH',
  B_ADDRESS_LINE_1: '89',
  B_ADDRESS_LINE_2: 'HOF St',
  B_TOWN_OR_CITY: 'Leeds',
  B_POSTCODE: 'L22 2LL',
  C_ADDRESS_LINE_1: '44',
  C_ADDRESS_LINE_2: 'Test St',
  C_TOWN_OR_CITY: 'Surrey',
  C_POSTCODE: 'GU27 1LX',
  D_ADDRESS_LINE_1: '55',
  D_ADDRESS_LINE_2: 'Automation St',
  D_TOWN_OR_CITY: 'Bristol',
  D_POSTCODE: 'BS11 9AX',
  TELEPHONE: '01616699548',
  CONTACT_EMAIL_ADDRESS: 'sas-hof-test@digital.homeoffice.gov.uk',
  LANDLORD_EMAIL: 'Landlord.TestEmail@digital.homeoffice.gov.uk',
  DOB_1978: '01/01/1978',
  NATIONALITY: 'Spain',
  REF_NUMBER: 'ZW9005196',
  REQUEST_NOTICE: 'Request Notice',
  CHECK_PERSON_IS_DISQUALIFIED: 'Check person is disqualified',
  REPORT_DISQUALIFIED_PERSON: 'Report disqualified person',
  TENANTS_MOVE_IN_DATE: '11/11/2015',
  DISQUALIFIED_NOTICE_DATE: '10/02/1982',
  TENANTS_MOVE_OUT_DATE: '18/10/2022',
  RESPONSE_YES: 'Yes',
  RESPONSE_NO: 'No',
  YOUR_ADDRESS: 'Your Address',
  USE_PROPERTY_ADDRESS: 'Use Property Address',
  LANDLORD: 'Landlord',
  AGENT: 'Agent',
  KEY_DETAILS: 'Key details',
  LANDLORD_DETAILS: 'Landlord details',
  NOTICE_REQUESTED_FOR_DETAILS: 'Notice requested for',
  TENANTS_WHO_HAVE_LEFT: 'Tenants who have left',
  TENANTS_YOU_ARE_CHECKING: 'Tenants you are checking',
} as const;
